global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 1m

  external_labels:
    monitor: 'codelab-monitor'
    query_log_file: query_log_file.log


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

#  - job_name: 'cadvisor'
#    static_configs:
#      - targets: ['cadvisor:8080']
#    metric_relabel_configs:
#      - source_labels: [__name__]
#        regex: 'container_(network|cpu|memory|fs|log).*'
#        action: keep

  - job_name: 'memcached_exporter'
    static_configs:
      - targets: ['memcached_exporter:9150']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'dok-memcached:11211'


  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'mysql_exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['mysql_exporter:9104']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://lists.devopskorea.com
        - https://docs.devopskorea.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
